[package]
name = "${TFSCLIENT_NAME}"
version = "${TFSCLIENT_VERSION}"
authors = ["${TFSCLIENT_AUTHOR}"]
license = "${TFSCLIENT_LICENSE}"
description = "${TFSCLIENT_DESCRIPTION}"
edition = "2018"
readme = "README.md"
homepage = "${TFSCLIENT_URL}"
repository = "${TFSCLIENT_URL}"
documentation = "https://docs.rs/${TFSCLIENT_NAME}"
categories = ["api-bindings", "science"]

[dependencies]
futures = "0.1.29"
grpcio = "0.4.6"
protobuf = "2.8.1"

[lib]
crate-type = ["rlib"]
